In [122]:
import pandas as pd
import numpy as np

In [123]:
df=pd.read_csv('fullok.csv')
df

,نوع ملک,متراژ,قیمت,قیمت(متر مربع),منطقه,سال ساخت,تعداد خواب,جهت ساختمان,نوع سند,طبقه,...,گرمایش,آب گرم,تاریخ انتشار,پارکینگ,آسانسور,لابی,انباری,latitude,longitude,سونا و جکوزی
0,آپارتمان,136.0,"12,500,000,000 تومان","91,900,000 تومان",امیرآباد تهران,1401.0,3 خواب,شمالی,رسمی تک برگ,4,...,داکت اسپلیت,پکیج,4 هفته پیش,پارکینگ,آسانسور,لابی,انباری,35.733903,51.394386,سالن اجتماعات
1,آپارتمان,108.0,"7,500,000,000 تومان","69,400,000 تومان",دولت تهران,1383.0,2 خواب,شمالی,رسمی تک برگ,2,...,شوفاژ,موتورخانه,3 هفته پیش,پارکینگ,بالکن,انباری,حیاط,35.780815,51.450526,درب ریموت
2,آپارتمان,71.0,"4,900,000,000 تومان","69,000,000 تومان",جنت آباد مرکزی تهران,1397.0,2 خواب,شمالی,رسمی تک برگ,1,...,شوفاژ,پکیج,3 هفته پیش,پارکینگ,آسانسور,انباری,بالکن,35.758078,51.301245,پنجره دو جداره
3,آپارتمان,135.0,"13,500,000,000 تومان","100,000,000 تومان",امیرآباد تهران,1401.0,3 خواب,جنوبی,رسمی تک برگ,2,...,داکت اسپلیت,پکیج,4 هفته پیش,آسانسور,پارکینگ,لابی,انباری,35.738292,51.398549,تهویه هوا
4,آپارتمان,117.0,"9,200,000,000 تومان","78,600,000 تومان",یوسف آباد تهران,1394.0,2 خواب,جنوبی,رسمی تک برگ,4,...,شوفاژ,پکیج,3 هفته پیش,پارکینگ,آسانسور,لابی,انباری,35.735418,51.400867,تهویه هوا
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6009,آپارتمان,71.0,"5,500,000,000 تومان","77,500,000 تومان",اباذر آیت الله کاشانی ، تهران,1401.0,2 خواب,شمالی,رسمی تک برگ,1,...,شوفاژ,پکیج,3 هفته پیش,پارکینگ,آسانسور,انباری,لابی,35.730518,51.326241,بالکن
6010,آپارتمان,95.0,"5,150,000,000 تومان","54,200,000 تومان",پونک تهران,1386.0,2 خواب,شمالی,رسمی تک برگ,2,...,شوفاژ,موتورخانه,3 هفته پیش,پارکینگ,آسانسور,انباری,بالکن,35.775800,51.322554,حیاط
6011,آپارتمان,120.0,"8,400,000,000 تومان","70,000,000 تومان",سعادت آباد تهران,1379.0,3 خواب,جنوبی,رسمی تک برگ,1,...,شوفاژ,موتورخانه,3 هفته پیش,پارکینگ,آسانسور,لابی,انباری,35.786190,51.380954,بالکن
6012,آپارتمان,120.0,"8,500,000,000 تومان","70,800,000 تومان",سعادت آباد تهران,1384.0,3 خواب,شمالی,رسمی تک برگ,4,...,داکت اسپلیت,آبگرمکن,3 هفته پیش,بالکن,پارکینگ,سرایدار,آسانسور,35.786190,51.380954,لابی
6013,آپارتمان,185.0,"17,500,000,000 تومان","94,600,000 تومان",سهروردی شمالی تهران,1401.0,3 خواب,جنوبی,رسمی تک برگ,4,...,داکت اسپلیت,پکیج,3 هفته پیش,پارکینگ,آسانسور,انباری,تهویه هوا,35.734180,51.432981,پنجره دو جداره

In [124]:
df['قیمت(متر مربع)'] = df['قیمت(متر مربع)'].str.replace('تومان', '')

In [125]:
df['قیمت'] = df['قیمت'].str.replace('تومان', '')

In [126]:
df['تعداد خواب'] = df['تعداد خواب'].str.replace('خواب', '')

In [127]:
df['نوع ملک'] = df['نوع ملک'].str.replace('آپارتمان', 'Apateman')

In [128]:
df['جهت ساختمان'] = df['جهت ساختمان'].str.replace('شمالی', 'North')

In [129]:
df['جهت ساختمان'] = df['جهت ساختمان'].str.replace('جنوبی', 'South')

In [130]:
df['جهت ساختمان'] = df['جهت ساختمان'].str.replace('شرقی', 'Eastern')

In [131]:
df['آب گرم'] = df['آب گرم'].str.replace('آبگرمکن', 'True')

In [132]:
df['آب گرم'] = df['آب گرم'].str.replace('پکیج', 'True')

In [133]:
df['آب گرم'] = df['آب گرم'].str.replace('موتورخانه', 'True')

In [134]:
df['جهت ساختمان'] = df['جهت ساختمان'].str.replace('غربی', 'western')

In [135]:
df['تاریخ انتشار'] = df['تاریخ انتشار'].str.replace('هفته پیش', 'last week')

In [136]:
df['تاریخ انتشار'] = df['تاریخ انتشار'].str.replace('روز پیش', 'last day ')

In [137]:
df['تاریخ انتشار'] = df['تاریخ انتشار'].str.replace('ماه پیش', 'last month ')

In [138]:
df['نوع سند'] = df['نوع سند'].str.replace('رسمی تک برگ', 'True')

In [139]:
df['نوع سند'] = df['نوع سند'].str.replace('رسمی منگوله دار', 'True')

In [140]:
df['نوع سند'] = df['نوع سند'].str.replace('غیر رسمی', 'False')

In [141]:
df['site']='https://shabesh.com/'

In [142]:
df.to_csv('final.csv')

In [143]:
df1=pd.read_csv('final.csv')

In [144]:
df1.head()

,Unnamed: 0,نوع ملک,متراژ,قیمت,قیمت(متر مربع),منطقه,سال ساخت,تعداد خواب,جهت ساختمان,نوع سند,...,آب گرم,تاریخ انتشار,پارکینگ,آسانسور,لابی,انباری,latitude,longitude,سونا و جکوزی,site
0,0,Apateman,136.0,"12,500,000,000","91,900,000",امیرآباد تهران,1401.0,3.0,North,True,...,True,4 last week,پارکینگ,آسانسور,لابی,انباری,35.733903,51.394386,سالن اجتماعات,https://shabesh.com/
1,1,Apateman,108.0,"7,500,000,000","69,400,000",دولت تهران,1383.0,2.0,North,True,...,True,3 last week,پارکینگ,بالکن,انباری,حیاط,35.780815,51.450526,درب ریموت,https://shabesh.com/
2,2,Apateman,71.0,"4,900,000,000","69,000,000",جنت آباد مرکزی تهران,1397.0,2.0,North,True,...,True,3 last week,پارکینگ,آسانسور,انباری,بالکن,35.758078,51.301245,پنجره دو جداره,https://shabesh.com/
3,3,Apateman,135.0,"13,500,000,000","100,000,000",امیرآباد تهران,1401.0,3.0,South,True,...,True,4 last week,آسانسور,پارکینگ,لابی,انباری,35.738292,51.398549,تهویه هوا,https://shabesh.com/
4,4,Apateman,117.0,"9,200,000,000","78,600,000",یوسف آباد تهران,1394.0,2.0,South,True,...,True,3 last week,پارکینگ,آسانسور,لابی,انباری,35.735418,51.400867,تهویه هوا,https://shabesh.com/

In [145]:
f1=df1.drop(['آسانسور', 'انباری','پارکینگ','لابی','سونا و جکوزی'],axis=1)

In [146]:
cols = ['پارکینگ', 'انباری', 'آسانسور','لابی','سونا و جکوزی']
df['combined'] = df[cols].apply(lambda row: '_'.join(row.values.astype(str)), axis=1)

In [147]:
final=df['combined'].str.get_dummies(sep='_')
final

,nan,آسانسور,آیفون تصویری,استخر,انباری,باربیکیو,بازسازی شده,بالکن,تهویه هوا,حیاط,...,قابل تبدیل,قدرالسهم,لابی,مال,معاوضه,موقعیت اداری,وامدار,پارکینگ,پنجره دو جداره,گرمایش مرکزی
0,0,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1,0,0,0,0,1,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
2,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,1,0
3,0,1,0,0,1,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
4,0,1,0,0,1,0,0,0,1,0,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6009,0,1,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
6010,0,1,0,0,1,0,0,1,0,1,...,0,0,0,0,0,0,0,1,0,0
6011,0,1,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
6012,0,1,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
6013,0,1,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,1,0

In [148]:
df3 = final.filter(['آسانسور', 'انباری','پارکینگ'])

In [149]:
ok=pd.merge(f1, df3, left_index=True, right_index=True)

In [150]:
df5 = ok.loc[:, ~ok.columns.str.contains('^Unnamed')]

In [151]:
df5

,نوع ملک,متراژ,قیمت,قیمت(متر مربع),منطقه,سال ساخت,تعداد خواب,جهت ساختمان,نوع سند,طبقه,...,سرمایش,گرمایش,آب گرم,تاریخ انتشار,latitude,longitude,site,آسانسور,انباری,پارکینگ
0,Apateman,136.0,"12,500,000,000","91,900,000",امیرآباد تهران,1401.0,3.0,North,True,4,...,داکت اسپلیت,داکت اسپلیت,True,4 last week,35.733903,51.394386,https://shabesh.com/,1,1,1
1,Apateman,108.0,"7,500,000,000","69,400,000",دولت تهران,1383.0,2.0,North,True,2,...,کولر آبی,شوفاژ,True,3 last week,35.780815,51.450526,https://shabesh.com/,0,1,1
2,Apateman,71.0,"4,900,000,000","69,000,000",جنت آباد مرکزی تهران,1397.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.758078,51.301245,https://shabesh.com/,1,1,1
3,Apateman,135.0,"13,500,000,000","100,000,000",امیرآباد تهران,1401.0,3.0,South,True,2,...,داکت اسپلیت,داکت اسپلیت,True,4 last week,35.738292,51.398549,https://shabesh.com/,1,1,1
4,Apateman,117.0,"9,200,000,000","78,600,000",یوسف آباد تهران,1394.0,2.0,South,True,4,...,کولر آبی,شوفاژ,True,3 last week,35.735418,51.400867,https://shabesh.com/,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6009,Apateman,71.0,"5,500,000,000","77,500,000",اباذر آیت الله کاشانی ، تهران,1401.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.730518,51.326241,https://shabesh.com/,1,1,1
6010,Apateman,95.0,"5,150,000,000","54,200,000",پونک تهران,1386.0,2.0,North,True,2,...,کولر آبی,شوفاژ,True,3 last week,35.775800,51.322554,https://shabesh.com/,1,1,1
6011,Apateman,120.0,"8,400,000,000","70,000,000",سعادت آباد تهران,1379.0,3.0,South,True,1,...,کولر گازی,شوفاژ,True,3 last week,35.786190,51.380954,https://shabesh.com/,1,1,1
6012,Apateman,120.0,"8,500,000,000","70,800,000",سعادت آباد تهران,1384.0,3.0,North,True,4,...,کولر گازی,داکت اسپلیت,True,3 last week,35.786190,51.380954,https://shabesh.com/,1,0,1
6013,Apateman,185.0,"17,500,000,000","94,600,000",سهروردی شمالی تهران,1401.0,3.0,South,True,4,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.734180,51.432981,https://shabesh.com/,1,1,1

In [152]:
df5.to_csv('final_file.csv')

In [153]:
final=pd.read_csv('final_file.csv')

In [154]:
df5 = final.loc[:, ~ok.columns.str.contains('^Unnamed')]

In [155]:
df5.head(30)

,نوع ملک,متراژ,قیمت,قیمت(متر مربع),منطقه,سال ساخت,تعداد خواب,جهت ساختمان,نوع سند,طبقه,...,سرمایش,گرمایش,آب گرم,تاریخ انتشار,latitude,longitude,site,آسانسور,انباری,پارکینگ
0,Apateman,136.0,"12,500,000,000","91,900,000",امیرآباد تهران,1401.0,3.0,North,True,4,...,داکت اسپلیت,داکت اسپلیت,True,4 last week,35.733903,51.394386,https://shabesh.com/,1,1,1
1,Apateman,108.0,"7,500,000,000","69,400,000",دولت تهران,1383.0,2.0,North,True,2,...,کولر آبی,شوفاژ,True,3 last week,35.780815,51.450526,https://shabesh.com/,0,1,1
2,Apateman,71.0,"4,900,000,000","69,000,000",جنت آباد مرکزی تهران,1397.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.758078,51.301245,https://shabesh.com/,1,1,1
3,Apateman,135.0,"13,500,000,000","100,000,000",امیرآباد تهران,1401.0,3.0,South,True,2,...,داکت اسپلیت,داکت اسپلیت,True,4 last week,35.738292,51.398549,https://shabesh.com/,1,1,1
4,Apateman,117.0,"9,200,000,000","78,600,000",یوسف آباد تهران,1394.0,2.0,South,True,4,...,کولر آبی,شوفاژ,True,3 last week,35.735418,51.400867,https://shabesh.com/,1,1,1
5,Apateman,90.0,"8,100,000,000","90,000,000",امیرآباد تهران,1400.0,2.0,South,True,3,...,داکت اسپلیت,داکت اسپلیت,True,4 last week,35.735801,51.393957,https://shabesh.com/,1,1,1
6,Apateman,135.0,"20,250,000,000","150,000,000",فرمانیه تهران,1401.0,3.0,South,True,5,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.803779,51.465119,https://shabesh.com/,1,1,1
7,Apateman,91.0,"5,700,000,000","62,600,000",پونک تهران,1393.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.742010,51.338876,https://shabesh.com/,1,1,1
8,Apateman,88.0,"7,070,000,000","80,300,000",پونک تهران,1401.0,2.0,South,True,2,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.761532,51.325840,https://shabesh.com/,1,1,1
9,Apateman,83.0,"7,800,000,000","94,000,000",اختیاریه تهران,1401.0,2.0,North,True,2,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.784995,51.451527,https://shabesh.com/,1,1,1
10,Apateman,93.0,"8,500,000,000","91,400,000",امیرآباد تهران,1399.0,2.0,South,True,1,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.733380,51.394773,https://shabesh.com/,1,1,1
11,Apateman,74.0,"4,620,000,000","62,400,000",جنت آباد شمالی تهران,1392.0,2.0,North,True,3,...,کولر آبی,شوفاژ,True,3 last week,35.772129,51.310058,https://shabesh.com/,1,1,1
12,Apateman,55.0,"3,360,000,000","61,100,000",بلوار فردوس تهران,1381.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.727460,51.313812,https://shabesh.com/,0,1,1
13,Apateman,64.0,"4,580,000,000","71,600,000",باغ فیض تهران,1397.0,1.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.744735,51.330366,https://shabesh.com/,1,1,1
14,Apateman,115.0,"11,150,000,000","97,000,000",یوسف آباد تهران,1400.0,2.0,North,True,2,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.728642,51.412421,https://shabesh.com/,1,1,1
15,Apateman,62.0,"4,000,000,000","64,500,000",آیت الله کاشانی تهران,1383.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.737860,51.289744,https://shabesh.com/,1,1,1
16,Apateman,82.0,"5,500,000,000","67,100,000",پونک تهران,1386.0,2.0,South,True,5,...,کولر آبی,شوفاژ,True,3 last week,35.748125,51.334656,https://shabesh.com/,1,1,1
17,Apateman,78.0,"4,900,000,000","62,800,000",بلوار فردوس تهران,1391.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.730028,51.300354,https://shabesh.com/,1,1,1
18,Apateman,127.0,"12,000,000,000","94,500,000",اختیاریه تهران,1398.0,2.0,North,True,2,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.783872,51.458016,https://shabesh.com/,1,1,1
19,Apateman,73.0,"4,650,000,000","63,700,000",جنت آباد مرکزی تهران,1383.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.759607,51.309156,https://shabesh.com/,1,1,1
20,Apateman,85.0,"4,650,000,000","54,700,000",سردار جنگل پونک ، تهران,1380.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.757878,51.326176,https://shabesh.com/,0,1,1
21,Apateman,80.0,"7,200,000,000","90,000,000",یوسف آباد تهران,1391.0,2.0,North,True,5,...,کولر آبی,شوفاژ,True,3 last week,35.729461,51.405684,https://shabesh.com/,1,1,1
22,Apateman,113.0,"7,400,000,000","65,500,000",امیرآباد تهران,1386.0,2.0,North,True,2,...,کولر آبی,شوفاژ,True,3 last week,35.733972,51.393571,https://shabesh.com/,1,1,1
23,Apateman,105.0,"10,500,000,000","100,000,000",یوسف آباد تهران,1400.0,2.0,South,True,1,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.729548,51.402133,https://shabesh.com/,1,1,1
24,Apateman,90.0,"9,000,000,000","100,000,000",اختیاریه تهران,1401.0,2.0,North,True,3,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.788484,51.459574,https://shabesh.com/,1,1,1
25,Apateman,155.0,"24,900,000,000","160,600,000",حکمت تهران,1401.0,3.0,South,True,5,...,فن کوئل,فن کوئل,True,3 last week,35.796374,51.433179,https://shabesh.com/,0,0,0
26,Apateman,66.0,"4,120,000,000","62,400,000",پونک تهران,1394.0,1.0,North,True,3,...,کولر آبی,شوفاژ,True,3 last week,35.745593,51.329399,https://shabesh.com/,1,1,1
27,Apateman,127.0,"5,850,000,000","46,100,000",پونک تهران,1385.0,2.0,North,True,1,...,کولر آبی,شوفاژ,True,3 last week,35.766523,51.333480,https://shabesh.com/,1,1,1
28,Apateman,115.0,"9,300,000,000","80,900,000",سهروردی شمالی تهران,1396.0,3.0,South,True,1,...,اسپلیت,شوفاژ,True,3 last week,35.731228,51.438664,https://shabesh.com/,1,1,1
29,Apateman,136.0,"12,500,000,000","91,900,000",امیرآباد تهران,1401.0,3.0,North,True,4,...,داکت اسپلیت,داکت اسپلیت,True,3 last week,35.734565,51.394172,https://shabesh.com/,1,1,1

In [156]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6014 entries, 0 to 6013
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   نوع ملک          5603 non-null   object
 1   متراژ            5603 non-null   float64
 2   قیمت             5603 non-null   object
 3   قیمت(متر مربع)   5603 non-null   object
 4   منطقه            5603 non-null   object
 5   سال ساخت         5603 non-null   float64
 6   تعداد خواب       5603 non-null   float64
 7   جهت ساختمان      5603 non-null   object
 8   نوع سند          5603 non-null   object
 9   طبقه             5603 non-null   object
 10  تعداد طبقات      5603 non-null   object
 11  سرویس بهداشتی    5603 non-null   object
 12  تعداد واحد طبقه  5603 non-null   object
 13  نوع کف           5603 non-null   object
 14  نما              5603 non-null   object
 15  سرمایش           5603 non-null   object
 16  گرمایش           5603 non-null   object
 17  آب گرم           5603 non-null   object
 18  تاریخ انتشار     5603 non-null   object
 19  latitude         5603 non-null   float64
 20  longitude        5603 non-null   float64
 21  site             6014 non-null   object
 22  آسانسور          6014 non-null   int64
 23  انباری           6014 non-null   int64
 24  پارکینگ          6014 non-null   int64
dtypes: float64(5), int64(3), object(17)
memory usage: 1.1+ MB

In [159]:
sum(df5.isnull().values.ravel())

8631

In [160]:
sum([True for idx,row in df5.iterrows() if any(row.isnull())])

411

In [165]:
df = df5[~df5.eq(' ').all(1)]

In [166]:
sum([True for idx,row in df.iterrows() if any(row.isnull())])

411

In [ ]:
df.mask(df.eq('')).dropna(thresh=1)